server:
  port: 9003
spring:
  application:
    name: configServices
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: https://LAPTOP-6V4RDUKD/svn/spring-cloud-repository/test/config
          username: admin
          password: 123456
          default-label:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:gi
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30